######################## default configuration ####################
baseURL = "/"
title = "Librezo"
theme = "foopgp-hugotheme"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# limit RSS feeds to 50 entries
rssLimit = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/fuse/fuse.js"


############################## navigation ###############################

# main menu
[[menu.main]]
weight = 1
name = "about"
hasChildren = true

  [[menu.main]]
  parent = "about"
  name = "Librezo"
  URL = "about"
  weight = 1

  [[menu.main]]
  parent = "about"
  name = "people"
  URL = "author"
  weight = 2

  [[menu.main]]
  parent = "about"
  name = "partners"
  URL = "partner"
  weight = 3

[[menu.main]]
name = "our services"
URL = "solutions"
weight = 2

#[[menu.main]]
#name = "trainings"
#URL = "course"
#weight = 3

[[menu.main]]
weight = 4
name = "events"
URL = "event"

[[menu.main]]
name = "blog"
URL = "blog"
weight = 5

# footer menu

[[menu.footer]]
name = "about"
URL = "about"

[[menu.footer]]
name = "contact"
URL = "contact"

[[menu.footer]]
name = "legal notice"
URL = "about/legal-notice"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Cooperative Tech Company"
#author = "Librezo"
# contact info
#address = "9567 Turner Trace Apt. BC C3G8A4"
#mobile = "+211234565523"
email = "info@librezo.fr"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false
searchURL = "search"

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

############################# social site ########################
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons

[[params.social]]
title = "home"
icon = "ti-home" # themify icon : https://themify.me/themify-icons
link = "/"

[[params.social]]
title = "contact"
icon = "ti-email" # themify icon : https://themify.me/themify-icons
link = "mailto:info@librezo.fr"

[[params.social]]
title = "code"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/librezo"

#[[params.social]]
#title = "follow us"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "https://twitter.com/librezo"

[[params.social]]
title = "chat"
icon = "ti-comments" # themify icon : https://themify.me/themify-icons
link = "https://chat.axiom-team.fr/group/librezo"

################################### English language #####################################
[Languages.en]
languageName = "en 🇺🇸 🇬🇧 ..."
languageCode = "en_US"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020. [Thanks](https://github.com/librezo/librezo-hugowebsite) to [Hugo](https://gohugo.io)"


################################### French language #####################################
[Languages.fr]
languageName = "fr 🇫🇷 🇨🇩 ..."
languageCode = "fr_FR"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2020. [Généré](https://github.com/librezo/librezo-hugowebsite) grâce à [Hugo](https://gohugo.io)"
